# Basic Information 
title: Huabin Liu
position: Ph.D student
affiliation: Shanghai Jiao Tong University
affiliation_link: https://en.sjtu.edu.cn/
#affiliation_logo: ./assets/img/university-logo-small-horizontal-white-156eae9527.svg
affiliation_logo: ./assets/img/sjtubannersilver.png
email: huabinliu (at) sjtu.edu.cn
# email2: h.liu3 (at) uva.nl

# Search Engine Optimization (SEO)
keywords: huabin liu, liu huabin, huabinliu, liuhuabin, huabin sjtu, huabinliu sjtu
canonical: https://www.cs.jhu.edu/~yyliu/
description: Huabin Liu is a fifth-year Ph.D student at Shanghai Jiao Tong University (SJTU). His research lies in few-shot video learning, video understanding, video reasoning & captioning.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=hicoLSQAAAAJ&hl
github_link: https://github.com/R00Kie-Liu
cv_link: ./CV_huabin.pdf
# linkedin: https://www.linkedin.com/in/liuyaoyao/
# twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar: ./assets/img/huabin_mini.jpg
favicon: ./assets/img/favicon-sjtu.png
favicon_dark: ./assets/img/favicon-sjtu-dark.png

# Footnotes
# footnote: Feel free to use my website's source code.
# footnote_link: https://github.com/yaoyao-liu/minimal-light

auto_dark_mode: true
# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

google_analytics: G-EPYNTGF9Y1

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
